version: '3'
services:
  server:
    build:
        context: .
    ports:
      - 8000:8000

  redis:
    image: redis:2.8.19
    hostname: redis
    expose:
      - "6379"

  celery:
    build:
      context: .
    command: celery -A movie_list worker -B -l info
    links:
      - redis