version: '2'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: movies
    expose:
      - 3306

  web:
    build:
        context: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    restart: always

  redis:
    image: redis:2.8.19
    hostname: redis
    expose:
      - "6379"

  celery:
    depends_on:
      - db
    build:
      context: .
    command: celery -A movie_list worker -B -l info
    links:
      - redis
      - db
