# Generated by Django 2.1 on 2018-08-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='movie_uid',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_characters',
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviecharacters',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
